// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ackavowpstepuxlmaymr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFja2F2b3dwc3RlcHV4bG1heW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDQ5NzQsImV4cCI6MjA2NTMyMDk3NH0.Evg9KwqTADEVe9U9xZT2lmpcLTsTxKGG8gXDboQCnvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);